apiVersion: v1
kind: Service
metadata:
  name: docker-demo
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 31080
  selector:
    app: docker-demo
    version: v1.0.1
  type: NodePort
