apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: docker-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docker-demo
  template:
    metadata:
      labels:
        app: docker-demo
    spec:
      containers:
        - name: docker-demo
          image: sundacheng/docker_demo:v1.0.1
#          env:
#            - name: MY_NODE_NAME
#              valueFrom:
#                fieldRef:
#                  fieldPath: spec.nodeName
#            - name: MY_POD_NAME
#              valueFrom:
#                fieldRef:
#                  fieldPath: metadata.name
#            - name: MY_POD_NAMESPACE
#              valueFrom:
#                fieldRef:
#                  fieldPath: metadata.namespace
#            - name: MY_POD_IP
#              valueFrom:
#                fieldRef:
#                  fieldPath: status.podIP
